/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ReputationRegistry,
  ReputationRegistryInterface,
} from "../../contracts/ReputationRegistry";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "agent",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newScore",
        type: "uint256",
      },
    ],
    name: "ScoreUpdated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "completedJobs",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "marketplace",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "agent",
        type: "address",
      },
    ],
    name: "reward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "score",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_marketplace",
        type: "address",
      },
    ],
    name: "setMarketplace",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50600280546001600160a01b031916331790556102f8806100326000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c806355f1f3101461005c5780636353586b1461008f57806373ad6c2d146100a4578063776f3843146100b7578063abc8c7af146100d7575b600080fd5b61007c61006a36600461026b565b60016020526000908152604090205481565b6040519081526020015b60405180910390f35b6100a261009d36600461026b565b610102565b005b6100a26100b236600461026b565b610200565b61007c6100c536600461026b565b60006020819052908152604090205481565b6002546100ea906001600160a01b031681565b6040516001600160a01b039091168152602001610086565b6002546001600160a01b031633146101545760405162461bcd60e51b815260206004820152601060248201526f4f6e6c79206d61726b6574706c61636560801b60448201526064015b60405180910390fd5b6001600160a01b03811660009081526020819052604081208054600a929061017d90849061029b565b90915550506001600160a01b038116600090815260016020819052604082208054919290916101ad90849061029b565b90915550506001600160a01b038116600081815260208181526040918290205491519182527f66ead48cfe0e1d1aa8bad492e906c348dfcfeecbf3b7b2cdf9b1f3cfa42a2945910160405180910390a250565b6002546001600160a01b031633146102495760405162461bcd60e51b815260206004820152600c60248201526b155b985d5d1a1bdc9a5e995960a21b604482015260640161014b565b600280546001600160a01b0319166001600160a01b0392909216919091179055565b60006020828403121561027d57600080fd5b81356001600160a01b038116811461029457600080fd5b9392505050565b808201808211156102bc57634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220e1115f541bfda17b19756b323a1a9d5e6dec4edc80e4ce46549e162d10ab1ac764736f6c63430008140033";

type ReputationRegistryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ReputationRegistryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ReputationRegistry__factory extends ContractFactory {
  constructor(...args: ReputationRegistryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ReputationRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ReputationRegistry__factory {
    return super.connect(runner) as ReputationRegistry__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ReputationRegistryInterface {
    return new Interface(_abi) as ReputationRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ReputationRegistry {
    return new Contract(address, _abi, runner) as unknown as ReputationRegistry;
  }
}
