import type { ExecutionContext, Tool } from "../types.ts";

export class CodeGeneratorTool
  implements Tool<{ prompt: string; research: string[] }, { filename: string; content: string }>
{
  name = "codeGenerator";

  async run(
    input: { prompt: string; research: string[] },
    context: ExecutionContext
  ): Promise<{ filename: string; content: string }> {
    const safeName = context.task.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
    const filename = `${safeName || "task"}-artifact.html`;
    const bullets = input.research.map((item) => `<li>${item}</li>`).join("");

    const content = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${context.task.title}</title>
    <style>
      :root { color-scheme: light; font-family: Georgia, serif; }
      body { margin: 0; background: linear-gradient(135deg, #f6efe4, #d9e7ff); color: #1b1a19; }
      main { max-width: 760px; margin: 4rem auto; padding: 3rem; background: rgba(255,255,255,0.82); border-radius: 24px; box-shadow: 0 24px 80px rgba(29, 33, 68, 0.18); }
      h1 { font-size: 3rem; margin-bottom: 1rem; }
      p, li { line-height: 1.6; font-size: 1.05rem; }
      .cta { display: inline-block; margin-top: 1.5rem; padding: 0.85rem 1.4rem; background: #1f4fd1; color: white; border-radius: 999px; text-decoration: none; }
    </style>
  </head>
  <body>
    <main>
      <p>Generated by marketplace worker agent</p>
      <h1>${context.task.title}</h1>
      <p>${input.prompt}</p>
      <ul>${bullets}</ul>
      <a class="cta" href="#demo">Launch Demo</a>
    </main>
  </body>
</html>`;

    return { filename, content };
  }
}
